### ISSUE TITLE
Validate TXTRegisterSpace

### ISSUE THREAD

**Issue by siro20** [9elements/txt-suite#22]
Validate the following before using them:
        SinitBase    uint32            // TXT.SINIT.BASE
        SinitSize    uint32            // TXT.SINIT.SIZE
        MleJoin      uint32            // TXT.MLE.JOIN
        HeapBase     uint32            // TXT.HEAP.BASE
        HeapSize     uint32            // TXT.HEAP.SIZE
        Dpr          DMAProtectedRange // TXT.DPR

Add additional test cases to validate the members.

**Comment by ChriMarMe** [comment]
Done in #58
