### ISSUE TITLE
Split tests into categories

### ISSUE THREAD

**Issue by zaolin** [9elements/txt-suite#50]
Hey there,

We have two Intel TXT implementation with different featureset to cover.
Let's introduce a section for pre coffeelake Intel TXT tests
Common tests
and CBnT tests

**Comment by ChriMarMe** [comment]
First step is done in #51. Further changes will be done in later PRs.

This change needs some major changes in txt-suite, so will take some effort to implement it.

**Comment by PatrickRudolph** [comment]
#102 Introduced an API to run test split into categories.
It supports TXTReady and TXTLegacyBoot enabled for now.
It will be extended with CBnT tests once available.
