### ISSUE TITLE
Fix HeaderLen test

### ISSUE THREAD

**Issue by PatrickRudolph** [9elements/txt-suite#64]
acm.HeaderLen must be a multiple of 4, not 64, see Software development guide, "Appendix A Intel ® TXT Execution Technology Authenticated Code Modules".

**Comment by PatrickRudolph** [comment]
acm.HeaderLen is in units of 4 bytes. The "User Area" is modulo 64 bytes, but it's unclrear how to retrive the User Area Len.

**Comment by ChriMarMe** [comment]
acm.Header.Size - acm.Header.HeaderLen - acm.Header.ScatchSize = "User Area"?

**Comment by ChriMarMe** [comment]
Right now, we're 16byte off. Either we read to much, the ACM is not aligned correctly or the ACM ist just larger than 128kb. Need to dive into that.
