### ISSUE TITLE
Fix: CPU supports TXT test

### ISSUE THREAD

**Issue by zaolin** [9elements/txt-suite#70]
Hey

the test crashes in my virtual machine with:

CPU supports TXT: panic: runtime error: index out of range

goroutine 1 [running]:
github.com/9elements/txt-suite/pkg/api.ArchitectureTXTSupport(0x0, 0x20, 0x12)
        /home/philipp.deppenwiese/projects/go/src/github.com/9elements/txt-suite/pkg/api/ark-intel.go:27 +0x4d3
github.com/9elements/txt-suite/pkg/test.TestCPUSupportsTXT(0xc0000bbe10, 0x0, 0x0)
        /home/philipp.deppenwiese/projects/go/src/github.com/9elements/txt-suite/pkg/test/cpu.go:160 +0xdf
github.com/9elements/txt-suite/pkg/test.(*Test).Run(0xbfc6e0, 0x1)
        /home/philipp.deppenwiese/projects/go/src/github.com/9elements/txt-suite/pkg/test/test.go:76 +0x697
main.run(0x0)
        /home/philipp.deppenwiese/projects/go/src/github.com/9elements/txt-suite/cmd/txt-suite/main.go:63 +0xa3
main.main()
        /home/philipp.deppenwiese/projects/go/src/github.com/9elements/txt-suite/cmd/txt-suite/main.go:103 +0x171

**Comment by ChriMarMe** [comment]
Maybe CPUID api doesn't work properly.
