### ISSUE TITLE
Fix TPM is present check

### ISSUE THREAD

**Issue by zaolin** [9elements/txt-suite#71]
Hey,

the TPM is present check is false interpreted, please check the code

**Comment by ChriMarMe** [comment]
What do you mean with false interpreted? 
The implementation checks if a connection exists, no matter what TPM (required).
Then it checks, if TPM1.2 is present (test is not required)
After that, it checks, if TPM2.0 is present (test is not required)
The last test checks if one of the tests above passed. (this test is required again)

**Comment by PatrickRudolph** [comment]
Checked code, tests are valid.
